-- Learn SQL Online - Excercise: Selecting Data

-- Select statement syntax
SELECT column1, column2, column3...
FROM table1, table2, table3...
WHERE condition1 AND condition2...

-- Select only the name of all students with a grade higher than 80
SELECT name FROM students WHERE grade > 80;